# https://probot.github.io/apps/settings/
repository:
  description: A repository I made for my first YouTube Short!
  homepage: https://cloudpup.dev
  has_issues: false
  has_wiki: false
  has_downloads: false
